### ISSUE TITLE
changing the font

### ISSUE THREAD

**Issue by ddritzenhoff** [Masellum/hugo-theme-nostyleplease#1]
hey, first I just wanted to thank you for porting over this theme!

Is there any procedure in place to change the font? I'm inexperienced with frontend development, so the few attempts I made all failed.

Once I find a solution, I'd also be happy to create a PR to extend the documentation on how to do this.

**Comment by Masellum** [comment]
Sorry for the late reply. Change the `monospace` in [this line of code](https://github.com/Masellum/hugo-theme-nostyleplease/blob/44f8ee0b7d882549d825ba135d5450f414b92520/assets/css/main.scss#L28) to the font family you like should be enough :)
