### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by 0x3st** [Masellum/hugo-theme-nostyleplease#2]
Thank you for designing such a brilliant theme, however I have some difficulties in installing the theme.
Can you detail the installation instruction?
I'm new to hugo and didn't know so much.

**Comment by 0x3st** [comment]
like which folder is necessary.

**Comment by Masellum** [comment]
The easiest way is to clone this repo (or add as a submodule) to themes/nostyleplease then append `theme = 'nostyleplease'` as a newline to config.toml.

**Comment by Masellum** [comment]
However, the directories named `content` and `images` of this theme is created to give a demo and can be safely deleted after you add a post by yourself.
