### ISSUE TITLE
Error with "hugo server": unclosed action

### ISSUE THREAD

**Issue by DrupalDoesNotExists** [Masellum/hugo-theme-nostyleplease#3]
Issue happens when trying to run Hugo server with default config and only theme installed in "layouts/partials/menu_item.html" at line 16.

`Error: add site dependencies: load resources: loading templates: "/home/my-user/hugosite/themes/nostylesplease/layouts/partials/menu_item.html:16:1": parse failed: template: partials/menu_item.html:16: unclosed action`

Version: Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
Possible solution: remove new lines in this part
```
{{ partial "post_list.html" (dict 
                "context" .
                "section" $item.post_list.section
                "limit" $item.post_list.limit
                "show_more" $item.post_list.show_more
                "show_more_text" $item.post_list.show_more_text
                "show_more_url" $item.post_list.show_more_url
                ) -}}```

**Comment by Masellum** [comment]
Fixed by merging #4. Thanks.
