### ISSUE TITLE
PRE overflowing parent without scrollbar and awful black background of code blocks

### ISSUE THREAD

**Issue by DrupalDoesNotExists** [Masellum/hugo-theme-nostyleplease#5]
![image](https://user-images.githubusercontent.com/88618532/211213882-8c7216f0-c231-434d-8a04-3c804ea0bcb2.png)

Possible solution: set ``overflow-x: auto`` for pre

# Also

``<code>`` sets awful black background for it's content.

**Comment by Masellum** [comment]
Sorry for the late reply. Thanks for the overflow problem. However, the black background for `<code>` is intended, as this can help to distinguish between inline code and normal text. From your screenshot, it seems that you set another background color for `<pre>`, and set the same background color for `<pre>` and `<code>` might help.

**Comment by Masellum** [comment]
The overflow problem is fixed by merging #4. Thanks.
